### ISSUE TITLE
Hint for Cake 2.5

### ISSUE THREAD

**Issue by rico3000** [awebdeveloper/cakephp-maintenance-mode#3]
Hello,

my work-a-round for CakePHP 2.5.3

In my bootstrap.php: 

```
Configure::write('Dispatcher.filters', array(
  'AssetDispatcher',
  'CacheDispatcher',
  'MaintenanceModeFilter',
));
```

And I rename the File MaintenanceMode.php to MaintenanceModeFilter.php and put it into app/Routing/Filter/ 

Now it worked for me!

**Comment by awebdeveloper** [comment]
Good to hear thay
