### ISSUE TITLE
Turn this into a real plugin

### ISSUE THREAD

**Issue by josegonzalez** [awebdeveloper/cakephp-maintenance-mode#4]
Please consider the following changes:
- Moving the filter into a `Lib/Routing/Filter` directory
- Adding a `composer.json`
- Adding a test!
- Adding your package to packagist.org

Here is an example plugin that does all these things: https://github.com/FriendsOfCake/cakephp-csvview

I'll add your plugin to plugins.cakephp.org once this is complete.

**Comment by awebdeveloper** [comment]
Sure

**Comment by dereuromark** [comment]
You can also add it to https://github.com/FriendsOfCake/awesome-cakephp

**Comment by dereuromark** [comment]
You should note that this is for CakePHP2.x only in your readme and composer file. Otherwise people might try this for 3.x and fail.
